// <auto-generated />
namespace TheLegend.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ask1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ask1));
        
        string IMigrationMetadata.Id
        {
            get { return "201312191925220_ask1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
