// <auto-generated />
namespace TheLegend.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class introdution : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(introdution));
        
        string IMigrationMetadata.Id
        {
            get { return "201312260025086_introdution"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
