// <auto-generated />
namespace TheLegend.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Mission_Users : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mission_Users));
        
        string IMigrationMetadata.Id
        {
            get { return "201401102057545_Mission_Users"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
